import jsLogo from '../images/jsLogo.svg'

export const selectAllPosts = () => {
  return blogData;
};

export const selectPostById = (id) => {
  return blogData.find((post) => post.id === parseInt(id));
};

export const blogData = [
  {
    id: 0,
    author: "Josh Thompson",
    title: "All About Accessibility",
    date: "2022-10-25T03:30Z",
    image: jsLogo,
    summary:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    article:
      "Esse officia est excepteur incididunt aliquip quis et et sunt elit nulla excepteur duis do. Laborum cupidatat qui ullamco ut in amet Lorem quis magna esse occaecat non pariatur esse. Consectetur Lorem qui et aliqua in Lorem aliquip voluptate deserunt. Mollit magna aliqua in occaecat dolor non cupidatat anim id. Ad occaecat reprehenderit consectetur irure eiusmod tempor mollit voluptate est ut aliquip veniam deserunt deserunt. Commodo deserunt ullamco excepteur excepteur fugiat Lorem proident proident nulla proident mollit sit. Non exercitation anim occaecat mollit eu minim aliqua id sunt ex ut ad excepteur mollit.Esse minim officia id eu incididunt amet ipsum ipsum ipsum ea cupidatat. Aliquip reprehenderit fugiat dolore consectetur irure voluptate proident aliqua qui do sunt ipsum id sunt. Dolore Lorem occaecat ullamco nulla fugiat nulla irure ut esse laboris. Ea voluptate excepteur aute fugiat deserunt anim quis mollit pariatur. Commodo ea deserunt exercitation anim proident exercitation dolore nulla quis irure amet. Reprehenderit ipsum et occaecat laborum excepteur tempor nulla dolor tempor tempor consectetur commodo.Velit proident ullamco sunt consequat reprehenderit in veniam quis nostrud minim. Reprehenderit proident consequat adipisicing labore ex adipisicing aliqua labore ea do commodo ad. Qui id non aute cupidatat ullamco reprehenderit laborum esse eu minim. Elit est anim labore fugiat labore ipsum deserunt duis consequat fugiat. Occaecat nostrud enim Lorem pariatur do anim incididunt non deserunt sit. Tempor labore veniam sint consequat aliqua sint consequat nulla dolor ad et laborum nisi.Enim enim dolor consequat in voluptate in aliquip id amet amet magna velit. Nulla incididunt nostrud enim reprehenderit veniam do ad incididunt reprehenderit est est nulla aute non. Ex sint dolore mollit ex aute magna labore culpa ipsum est adipisicing. Ut consectetur aliqua occaecat ut aute fugiat eiusmod culpa proident dolor culpa irure. Anim voluptate dolore sit eu cillum do fugiat non cupidatat culpa exercitation magna ipsum. Laborum id ullamco laborum nisi officia laborum dolore culpa ullamco tempor.Voluptate dolor sint nostrud ea consequat dolor esse exercitation laboris Lorem sint et. Pariatur consectetur qui ipsum laboris eiusmod non esse et ea laboris Lorem irure est non. Nisi aliquip Lorem pariatur esse dolor aliqua et veniam aute culpa nostrud in. Aliqua mollit consectetur aute proident dolore ut commodo aliquip exercitation duis voluptate. Sint in laboris elit quis excepteur dolore anim adipisicing voluptate in consequat est sunt aliqua. Et laborum fugiat magna irure velit commodo cupidatat ea quis. Commodo dolor sint aliquip deserunt laboris labore irure Lorem labore laborum.",
  },
  {
    id: 1,
    author: "Josh Thompson",
    title: "All About Accessibility",
    date: "2022-8-25T03:30Z",
    image: jsLogo,
    summary:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    article:
      "Esse officia est excepteur incididunt aliquip quis et et sunt elit nulla excepteur duis do. Laborum cupidatat qui ullamco ut in amet Lorem quis magna esse occaecat non pariatur esse. Consectetur Lorem qui et aliqua in Lorem aliquip voluptate deserunt. Mollit magna aliqua in occaecat dolor non cupidatat anim id. Ad occaecat reprehenderit consectetur irure eiusmod tempor mollit voluptate est ut aliquip veniam deserunt deserunt. Commodo deserunt ullamco excepteur excepteur fugiat Lorem proident proident nulla proident mollit sit. Non exercitation anim occaecat mollit eu minim aliqua id sunt ex ut ad excepteur mollit.Esse minim officia id eu incididunt amet ipsum ipsum ipsum ea cupidatat. Aliquip reprehenderit fugiat dolore consectetur irure voluptate proident aliqua qui do sunt ipsum id sunt. Dolore Lorem occaecat ullamco nulla fugiat nulla irure ut esse laboris. Ea voluptate excepteur aute fugiat deserunt anim quis mollit pariatur. Commodo ea deserunt exercitation anim proident exercitation dolore nulla quis irure amet. Reprehenderit ipsum et occaecat laborum excepteur tempor nulla dolor tempor tempor consectetur commodo.Velit proident ullamco sunt consequat reprehenderit in veniam quis nostrud minim. Reprehenderit proident consequat adipisicing labore ex adipisicing aliqua labore ea do commodo ad. Qui id non aute cupidatat ullamco reprehenderit laborum esse eu minim. Elit est anim labore fugiat labore ipsum deserunt duis consequat fugiat. Occaecat nostrud enim Lorem pariatur do anim incididunt non deserunt sit. Tempor labore veniam sint consequat aliqua sint consequat nulla dolor ad et laborum nisi.Enim enim dolor consequat in voluptate in aliquip id amet amet magna velit. Nulla incididunt nostrud enim reprehenderit veniam do ad incididunt reprehenderit est est nulla aute non. Ex sint dolore mollit ex aute magna labore culpa ipsum est adipisicing. Ut consectetur aliqua occaecat ut aute fugiat eiusmod culpa proident dolor culpa irure. Anim voluptate dolore sit eu cillum do fugiat non cupidatat culpa exercitation magna ipsum. Laborum id ullamco laborum nisi officia laborum dolore culpa ullamco tempor.Voluptate dolor sint nostrud ea consequat dolor esse exercitation laboris Lorem sint et. Pariatur consectetur qui ipsum laboris eiusmod non esse et ea laboris Lorem irure est non. Nisi aliquip Lorem pariatur esse dolor aliqua et veniam aute culpa nostrud in. Aliqua mollit consectetur aute proident dolore ut commodo aliquip exercitation duis voluptate. Sint in laboris elit quis excepteur dolore anim adipisicing voluptate in consequat est sunt aliqua. Et laborum fugiat magna irure velit commodo cupidatat ea quis. Commodo dolor sint aliquip deserunt laboris labore irure Lorem labore laborum.",
  },
  {
    id: 2,
    author: "Josh Thompson",
    title: "All About Accessibility",
    date: "2022-7-25T12:30Z",
    image: jsLogo,
    summary:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    article:
      "Esse officia est excepteur incididunt aliquip quis et et sunt elit nulla excepteur duis do. Laborum cupidatat qui ullamco ut in amet Lorem quis magna esse occaecat non pariatur esse. Consectetur Lorem qui et aliqua in Lorem aliquip voluptate deserunt. Mollit magna aliqua in occaecat dolor non cupidatat anim id. Ad occaecat reprehenderit consectetur irure eiusmod tempor mollit voluptate est ut aliquip veniam deserunt deserunt. Commodo deserunt ullamco excepteur excepteur fugiat Lorem proident proident nulla proident mollit sit. Non exercitation anim occaecat mollit eu minim aliqua id sunt ex ut ad excepteur mollit.Esse minim officia id eu incididunt amet ipsum ipsum ipsum ea cupidatat. Aliquip reprehenderit fugiat dolore consectetur irure voluptate proident aliqua qui do sunt ipsum id sunt. Dolore Lorem occaecat ullamco nulla fugiat nulla irure ut esse laboris. Ea voluptate excepteur aute fugiat deserunt anim quis mollit pariatur. Commodo ea deserunt exercitation anim proident exercitation dolore nulla quis irure amet. Reprehenderit ipsum et occaecat laborum excepteur tempor nulla dolor tempor tempor consectetur commodo.Velit proident ullamco sunt consequat reprehenderit in veniam quis nostrud minim. Reprehenderit proident consequat adipisicing labore ex adipisicing aliqua labore ea do commodo ad. Qui id non aute cupidatat ullamco reprehenderit laborum esse eu minim. Elit est anim labore fugiat labore ipsum deserunt duis consequat fugiat. Occaecat nostrud enim Lorem pariatur do anim incididunt non deserunt sit. Tempor labore veniam sint consequat aliqua sint consequat nulla dolor ad et laborum nisi.Enim enim dolor consequat in voluptate in aliquip id amet amet magna velit. Nulla incididunt nostrud enim reprehenderit veniam do ad incididunt reprehenderit est est nulla aute non. Ex sint dolore mollit ex aute magna labore culpa ipsum est adipisicing. Ut consectetur aliqua occaecat ut aute fugiat eiusmod culpa proident dolor culpa irure. Anim voluptate dolore sit eu cillum do fugiat non cupidatat culpa exercitation magna ipsum. Laborum id ullamco laborum nisi officia laborum dolore culpa ullamco tempor.Voluptate dolor sint nostrud ea consequat dolor esse exercitation laboris Lorem sint et. Pariatur consectetur qui ipsum laboris eiusmod non esse et ea laboris Lorem irure est non. Nisi aliquip Lorem pariatur esse dolor aliqua et veniam aute culpa nostrud in. Aliqua mollit consectetur aute proident dolore ut commodo aliquip exercitation duis voluptate. Sint in laboris elit quis excepteur dolore anim adipisicing voluptate in consequat est sunt aliqua. Et laborum fugiat magna irure velit commodo cupidatat ea quis. Commodo dolor sint aliquip deserunt laboris labore irure Lorem labore laborum.",
  },
  {
    id: 3,
    author: "Josh Thompson",
    title: "All About Accessibility",
    date: "2018-6-25T08:30Z",
    image: jsLogo,
    summary:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    article:
      "Esse officia est excepteur incididunt aliquip quis et et sunt elit nulla excepteur duis do. Laborum cupidatat qui ullamco ut in amet Lorem quis magna esse occaecat non pariatur esse. Consectetur Lorem qui et aliqua in Lorem aliquip voluptate deserunt. Mollit magna aliqua in occaecat dolor non cupidatat anim id. Ad occaecat reprehenderit consectetur irure eiusmod tempor mollit voluptate est ut aliquip veniam deserunt deserunt. Commodo deserunt ullamco excepteur excepteur fugiat Lorem proident proident nulla proident mollit sit. Non exercitation anim occaecat mollit eu minim aliqua id sunt ex ut ad excepteur mollit.Esse minim officia id eu incididunt amet ipsum ipsum ipsum ea cupidatat. Aliquip reprehenderit fugiat dolore consectetur irure voluptate proident aliqua qui do sunt ipsum id sunt. Dolore Lorem occaecat ullamco nulla fugiat nulla irure ut esse laboris. Ea voluptate excepteur aute fugiat deserunt anim quis mollit pariatur. Commodo ea deserunt exercitation anim proident exercitation dolore nulla quis irure amet. Reprehenderit ipsum et occaecat laborum excepteur tempor nulla dolor tempor tempor consectetur commodo.Velit proident ullamco sunt consequat reprehenderit in veniam quis nostrud minim. Reprehenderit proident consequat adipisicing labore ex adipisicing aliqua labore ea do commodo ad. Qui id non aute cupidatat ullamco reprehenderit laborum esse eu minim. Elit est anim labore fugiat labore ipsum deserunt duis consequat fugiat. Occaecat nostrud enim Lorem pariatur do anim incididunt non deserunt sit. Tempor labore veniam sint consequat aliqua sint consequat nulla dolor ad et laborum nisi.Enim enim dolor consequat in voluptate in aliquip id amet amet magna velit. Nulla incididunt nostrud enim reprehenderit veniam do ad incididunt reprehenderit est est nulla aute non. Ex sint dolore mollit ex aute magna labore culpa ipsum est adipisicing. Ut consectetur aliqua occaecat ut aute fugiat eiusmod culpa proident dolor culpa irure. Anim voluptate dolore sit eu cillum do fugiat non cupidatat culpa exercitation magna ipsum. Laborum id ullamco laborum nisi officia laborum dolore culpa ullamco tempor.Voluptate dolor sint nostrud ea consequat dolor esse exercitation laboris Lorem sint et. Pariatur consectetur qui ipsum laboris eiusmod non esse et ea laboris Lorem irure est non. Nisi aliquip Lorem pariatur esse dolor aliqua et veniam aute culpa nostrud in. Aliqua mollit consectetur aute proident dolore ut commodo aliquip exercitation duis voluptate. Sint in laboris elit quis excepteur dolore anim adipisicing voluptate in consequat est sunt aliqua. Et laborum fugiat magna irure velit commodo cupidatat ea quis. Commodo dolor sint aliquip deserunt laboris labore irure Lorem labore laborum.",
  },
];
